### ISSUE TITLE
Old commands

### ISSUE THREAD

**Issue by srnyx** [srnyx/venox#5]
Transfer some of the commands from old Venox to new Venox with slash commands

**Comment by DWAA1660** [comment]
> Transfer some of the commands from old Venox to new Venox with slash commands

What do you mean what was in old venox

**Comment by srnyx** [comment]
> > Transfer some of the commands from old Venox to new Venox with slash commands
> 
> What do you mean what was in old venox

I don't remember, @Chrizxz would be the only one to do this

**Comment by Chrizxz** [comment]
> > > Transfer some of the commands from old Venox to new Venox with slash commands
> > 
> > What do you mean what was in old venox
> 
> I don't remember, @Chrizxz would be the only one to do this

I already transferred them to ja but if we are doin py then it keep this issue open for converting Js cmds to put cmds. If that's already done then u can close this.

**Comment by srnyx** [comment]
> if we are doin py then it keep this issue open for converting Js cmds to put cmds. If that's already done then u can close this.

I'll close this and make a new issue for JS to PY.
