### ISSUE TITLE
Dynamic slowmode

### ISSUE THREAD

**Issue by srnyx** [srnyx/venox#9]
Will change the Discord slowmode based on the chat's speed.
Ability to set a minimum and maximum value for each channel.
And the ability to toggle it for certain channels (disabled by default).

**Comment by DWAA1660** [comment]
@srnyx done

**Comment by srnyx** [comment]
> @srnyx done

Minimum and maximum was added?

**Comment by DWAA1660** [comment]
> > @srnyx done
> 
> Minimum and maximum was added?

in terroids newest pr the minimum is maximum minus 10

**Comment by srnyx** [comment]
> in terroids newest pr the minimum is maximum minus 10

And it's configurable per channel?

**Comment by DWAA1660** [comment]
> > in terroids newest pr the minimum is maximum minus 10
> 
> And it's configurable per channel?

the max yes

**Comment by srnyx** [comment]
> the max yes

What about the minimum?

**Comment by DWAA1660** [comment]
> > the max yes
> 
> What about the minimum?

its 10 minus the maximum

**Comment by srnyx** [comment]
> its 10 minus the maximum

Both need to be configurable. I'm going to want a minimum of 3 and a maximum of 8 for example. That would be impossible to do.

**Comment by DWAA1660** [comment]
This is added and both is configurable
